[package]
name = "rs-chip8"
version = "0.1.0"
authors = ["Valerio Pipolo <valep27@gmail.com>"]

[dependencies]
rand = "0.3.15"
clap = "~2.19.0"

[dependencies.sdl2]
version = "0.29"
default-features = false
features = ["gfx"]